# Generated by Django 5.2.15 on 2026-06-28 03:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='pdfs/', validators=[api.models.validate_pdf]),
        ),
    ]
